<?php

namespace AppBundle\Repository;

/**
 * CallcenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallcenterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findList()
    {
        return $this->createQueryBuilder('c')
                    ->addSelect('count(c.id)')
                    ->groupBy('c.date')
                    ->orderBy('c.publieLe', 'DESC')
                    ->getQuery()->getResult()
            ;
    }
}
