<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function compteur($zone = null)
    {
        return $this->createQueryBuilder('c')
                    ->select('count(c.id)')
                    ->innerJoin('c.rapport', 'r')
                    ->where('r.zone = :zone')
                    ->setParameters([
                        'zone'=> $zone
                    ])
                    ->getQuery()->getSingleScalarResult()
            ;
    }
}
