<?php

namespace AppBundle\Repository;

/**
 * StatitistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste journalière des statistiques
     */
    public function findByDay()
    {
        return $this->createQueryBuilder('s')
                    ->addSelect('SUM(s.valeur)')
                    ->where('s.statut = 1')
                    ->groupBy('s.date')
                    ->orderBy('s.publieLe', 'DESC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Calcul des statistique
     */
    public function objectifAction($slug = null)
    {
        if ($slug){
            return $this->createQueryBuilder('s')
                        ->select('SUM(s.valeur)')
                        ->leftJoin('s.zone', 'z')
                        ->where('z.slug LIKE :zone')
                        ->setParameter('zone', '%'.$slug.'%')
                        ->getQuery()->getSingleScalarResult()
                ;
        }else{
            return $this->createQueryBuilder('s')
                ->select('SUM(s.valeur)')
                ->getQuery()->getSingleScalarResult()
                ;
        }
    }
}
