<?php

namespace AppBundle\Repository;

/**
 * ZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function findList()
    {
        return $this->createQueryBuilder('z')->orderBy('z.libelle', 'ASC')->getQuery()->getResult();
    }

    public function findZone()
    {
        return $this->createQueryBuilder('z')->orderBy('z.libelle', 'ASC');
    }
}
